CREATE TABLE IF NOT EXISTS `wp_shop_user` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`ctime`  int(10) NOT NULL  COMMENT '创建时间',
`nickname`  varchar(255) NOT NULL  COMMENT '昵称',
`openid`  varchar(255) NOT NULL  COMMENT '微信用户的openid',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`address`  varchar(255) NOT NULL  COMMENT '地址',
`phone`  varchar(255) NOT NULL  COMMENT '电话',
`remain_money`  int(10) NOT NULL  COMMENT '账户余额',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_user` (`id`,`openid`,`nickname`,`phone`,`address`,`ctime`,`token`,`remain_money`) VALUES ('1','-1','张三','123456','浦东新区','0','gh_b6ff5c2aaf62','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_user','微商用户','0','','1','{"1":["ctime","nickname","openid","token","address","phone","remain_money"]}','1:基础','','','','','','10','','','1437701471','1438338454','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','创建时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1437701869','1437701869','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('nickname','昵称','varchar(255) NOT NULL','string','','昵称','1','','0','0','1','1437701780','1437701780','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','微信用户的openid','varchar(255) NOT NULL','string','','微信用户openid','1','','0','0','1','1437701744','1437701744','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','1','','0','0','1','1437701886','1437701886','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('address','地址','varchar(255) NOT NULL','string','','地址','1','','0','0','1','1437701843','1437701843','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','电话','varchar(255) NOT NULL','string','','电话','1','','0','0','1','1437701814','1437701814','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('remain_money','账户余额','int(10) NOT NULL','num','','余额','1','','0','0','1','1438338265','1438338265','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_shop_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(255) NOT NULL  COMMENT '商品名称',
`count`  int(10) NOT NULL  COMMENT '商品数量',
`fid`  int(10) NOT NULL  COMMENT '订单的fid',
`userinfo`  text NOT NULL  COMMENT '收件人信息',
`order_status`  char(50) NOT NULL  COMMENT '订单状态',
`timestamp`  int(10) NOT NULL  COMMENT '下单时间',
`user_id`  int(10) NOT NULL  COMMENT '用户id',
`ip`  varchar(255) NOT NULL  COMMENT '支付ip',
`total_fee`  int(10) NOT NULL  COMMENT '总费用',
`product_field`  text NOT NULL  COMMENT '商品',
`unit_price`  int(10) NOT NULL  COMMENT '单价',
`pid`  int(10) NOT NULL  COMMENT '商品id',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('7','1','水果','50','192.168.1.106','1437832720','inorder','{"openid":-1,"nickname":"x","phone":"c","address":"d","ctime":"2015-07-25 21:58:40"}','0','1','','0','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('8','1','水果','150','192.168.1.106','1437833307','inorder','{"openid":-1,"nickname":"\u5c0f\u660e","phone":"1234565","address":"\u5730\u4e2d\u6d77","ctime":"2015-07-25 22:08:27"}','0','1','','0','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('9','1','龙岩','150','192.168.1.106','1437833307','inorder','{"openid":-1,"nickname":"\u5c0f\u660e","phone":"1234565","address":"\u5730\u4e2d\u6d77","ctime":"2015-07-25 22:08:27"}','8','1','','0','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('4','1','水果','50','192.168.1.106','1437832405','paied','{"openid":-1,"nickname":"x","phone":"c","address":"d","ctime":"2015-07-25 21:53:25"}','0','0','','0','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('5','1','水果','50','192.168.1.106','1437832445','inorder','{"openid":-1,"nickname":"x","phone":"c","address":"d","ctime":"2015-07-25 21:54:05"}','0','0','','0','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('6','1','水果','50','192.168.1.106','1437832485','inorder','{"openid":-1,"nickname":"x","phone":"c","address":"d","ctime":"2015-07-25 21:54:45"}','0','0','','0','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('10','1','龙岩','270','192.168.1.105','1437899226','inorder','{"openid":-1,"nickname":"xiaoli","phone":"123456","address":"xxddeed","ctime":"2015-07-26 16:27:06"}','0','6','龙岩','0','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('11','1','龙岩','370','192.168.1.105','1437900860','inorder','{"openid":-1,"nickname":"\u5c0f\u674e","phone":"12345","address":"\u4f11\u606f\u4f11\u606f\u4f11\u606f\u4f11\u606f","ctime":"2015-07-26 16:54:20"}','0','6','龙岩','45','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('12','1','龙岩','370','192.168.1.105','1437900860','inorder','{"openid":-1,"nickname":"\u5c0f\u674e","phone":"12345","address":"\u4f11\u606f\u4f11\u606f\u4f11\u606f\u4f11\u606f","ctime":"2015-07-26 16:54:20"}','11','1','龙岩','100','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('13','1','龙岩','270','192.168.1.105','1437901021','orderOk','{"openid":-1,"nickname":"xiaoli","phone":"123456","address":"xxddeed","ctime":"2015-07-26 16:57:01"}','0','6','龙岩','45','0');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`) VALUES ('14','1','龙岩','100','192.168.1.105','1437901021','cancled','{"openid":-1,"nickname":"xiaoli","phone":"123456","address":"xxddeed","ctime":"2015-07-26 16:57:01"}','13','1','龙岩','100','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_order','微商店订单','0','','1','{"1":["order_status","timestamp","user_id","ip","total_fee","userinfo"]}','1:基础','','','','','id:ID\r\nip:支付ip\r\ntotal_fee:总费用\r\ntimestamp:下单时间\r\nproduct_field:订单货物详情\r\nuserinfo:用户信息(用户名-电话-地址)\r\norder_status:订单状态','10','','','1437698180','1437827144','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','商品名称','varchar(255) NOT NULL','string','','商品名称','1','','0','0','1','1437895825','1437895825','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('count','商品数量','int(10) NOT NULL','num','','商品数量','1','','0','0','1','1437831288','1437831288','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('fid','订单的fid','int(10) NOT NULL','num','','订单的父id','1','','0','0','1','1437831058','1437831058','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('userinfo','收件人信息','text NOT NULL','textarea','','收件人信息','1','','0','0','1','1437725908','1437725908','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('order_status','订单状态','char(50) NOT NULL','textarea','','订单状态1.inorder,2.paied,3.returnGoods,4.agreereturn,','1','','0','0','1','1438229712','1437698629','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('timestamp','下单时间','int(10) NOT NULL','date','','下单时间','1','','0','0','1','1437698570','1437698570','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('user_id','用户id','int(10) NOT NULL','num','','用户id','1','','0','1','1','1437698325','1437698325','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ip','支付ip','varchar(255) NOT NULL','string','','支付ip','1','','0','0','1','1437698530','1437698530','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('total_fee','总费用','int(10) NOT NULL','num','','总费用','1','','0','0','1','1437698489','1437698489','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('product_field','商品','text NOT NULL','textarea','','商品信息','0','','0','0','1','1437698461','1437698461','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('unit_price','单价','int(10) NOT NULL','num','','单价','1','','0','0','1','1437899991','1437899991','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pid','商品id','int(10) NOT NULL','num','','商品id','1','','0','0','1','1438263721','1438263721','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;
CREATE TABLE IF NOT EXISTS `wp_shop_comments` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`gid`  int(10) NOT NULL  COMMENT '商品id',
`comments`  text NOT NULL  COMMENT '评论内容',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`ctime`  int(10) NOT NULL  COMMENT '时间',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_comments','商品评价','0','','1','','1:基础','','','','','','10','','','1438246940','1438246940','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('gid','商品id','int(10) NOT NULL','num','','商品id','1','','0','0','1','1438251563','1438247021','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('comments','评论内容','text NOT NULL','textarea','','评论','1','','0','0','1','1438247061','1438247061','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','1','','0','0','1','1438248787','1438248737','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','时间','int(10) NOT NULL','datetime','','评论的时间','1','','0','0','1','1438248818','1438248818','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;